### ISSUE TITLE
How to train the model on single GPU?

### ISSUE THREAD

**Issue by zhixuanli** [CoinCheung/DeepLabv3plus#2]
This ninja error continuously occurs:

`Command '['ninja', '-v']' returned non-zero exit status 1 `

As the instruction of the inplace_abn author: https://github.com/mapillary/inplace_abn/issues/106

I have to change the GCC version to 7.3.

But I'm not the root of the server, so I could not install any new GCC.

How can I train your code on a single GPU? I have a GPU on my own machine.

Thank you so much for your neat codes!

**Comment by CoinCheung** [comment]
Hi,
I dont think you can train this code on single gpu, since I used batch size of 8 on two 1080ti gpus.  If you train on one gpu, you will have to endure a batch size of 4 which will significantly harm the performance of BN based models. Therefore, I do not recommend you to try it.

**Comment by zhixuanli** [comment]
Thank you!
