### ISSUE TITLE
errors when running the code

### ISSUE THREAD

**Issue by pgu-nd** [CoinCheung/DeepLabv3plus#7]
I am trying to run the code, the following errors appear: FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja', RuntimeError: Ninja is required to load C++ extensions. Any ideas  to solve it will be highly appreciated. Thank you so much.

**Comment by pgu-nd** [comment]
My job submission script is: 
CUDA_VISIBLE_DEVICES=0,1,2
module load pytorch/1.1.0
python3 train.py

**Comment by CoinCheung** [comment]
answered in this issue:  #5
